### ISSUE TITLE
keyError: consensus_minimum

### ISSUE THREAD

**Issue by xyloforce** [nanoporetech/pipeline-nanopore-denovo-isoforms#2]
Hello,

The config.yml seems to lack a "consensus_minimum" key, according to the logfile. Is it really the case ? What are the allowed values ?
Thanks in advance !
P.S : attached is the logfile.
[slurm-1382776.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/4981260/slurm-1382776.txt)

**Comment by abayega** [comment]
Hi,
did you solve this issue?

> Hello,
> 
> The config.yml seems to lack a "consensus_minimum" key, according to the logfile. Is it really the case ? What are the allowed values ?
> Thanks in advance !
> P.S : attached is the logfile.
> [slurm-1382776.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/4981260/slurm-1382776.txt)

**Comment by xyloforce** [comment]
I solved it, if I remember well (it was during a summer internship), by adding the aforementionned key in the config file with a value of 20, the default for the closest option in isonclust2 (--low-cons-size)

**Comment by splaisan** [comment]
added `consensus_minimum: 20`
then crashes on consensus_maximum
any value for that one?
thanks in advance

**Comment by abayega** [comment]
In one of the scripts he uses -150. IsNoClust uses 150 if you check its
default parameters

**Comment by splaisan** [comment]
thanks @abayega ,
Yes running with 150 for max worked, but, unfortunately I bumped against a new problem which is that 87% of my reads were found 'unused' in the cdna_classifier_report, suggesting that only 13% of my data was used (see https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/issues/8).

I suspect that my input data was not as required (comes from a flongle) or that I did not understand the method correctly.

I hope someone with good experience of that pipeline will help me progress

Best regards

**Comment by abayega** [comment]
This is coming from Pychopper which scans the cDNA sequences looking for adapters and tries to find those that match the ones it has within it's 'database'. You might have run basecalling with the option to trim adapters selected. Here, Pychopper will not find any adapters (since they were trimmed) and it will report that most reads are not usable. Get the raw files again, basecall them locally without trimming adapters and rerun the pipeline

**Comment by splaisan** [comment]
Yes, if you look in issue 8 I reran the guppy basecalling with an extra option `--trim_strategy none` in order to try compensate for this but got no better results (still 87% out). I only do not know if this extra option was the right one ands nobody answered my issue yet. 
Do you know how to basecall in order to be compatible with pychopper (please look at my command in issue 8). 
Thanks

**Comment by abayega** [comment]
Which kit did you use for library preparation? Is it direct RNA or cDNA? I think the issue is to make sure that the adapters in the kit are also in the Pychoper database. I hope you did not use custom adapters.

**Comment by splaisan** [comment]
As written in issue 8 we used (SQK-DCS109) without any extras

**Comment by bsipos** [comment]
The commit https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/commit/d8506898bcc2e3f0284345301fbd886e0fa7486d fixes the original issue of the missing config parameters.
